# Island-mac Ghostty — {{THEME_NAME}}
# Generated by island-theme-set. Edit the template, not this file:
#   templates/ghostty-config.tpl

theme = {{THEME_GHOSTTY}}
background = {{THEME_BG}}

# Keep Option as a compose key so Option+L = @ etc. on a German layout.
macos-option-as-alt = false

font-family = JetBrainsMono Nerd Font
font-size = 13

window-padding-x = 8
window-padding-y = 8

cursor-style = block
cursor-style-blink = false
window-theme = dark
background-opacity = 0.97
background-blur = true
confirm-close-surface = false

mouse-scroll-multiplier = 0.95
