# Island-mac Ghostty — {{THEME_NAME}}
# Generated by island-theme-set. Edit the template, not this file:
#   templates/ghostty-config.tpl

theme = {{THEME_GHOSTTY}}
background = {{THEME_BG}}

# Keep Option as a compose key so Option+L = @ etc. on a German layout.
macos-option-as-alt = false

font-family = JetBrainsMono Nerd Font
font-size = 16

# Clean titlebar: blank the title text and hide the folder proxy icon.
title = " "
macos-titlebar-proxy-icon = hidden

window-padding-x = 8
window-padding-y = 8

cursor-style = block
cursor-style-blink = false
window-theme = dark
background-opacity = 0.97
background-blur = true
confirm-close-surface = false

mouse-scroll-multiplier = 0.95

# Ctrl+Shift+F -> tmux-sessionizer. The terminal cannot tell Ctrl+Shift+F from
# Ctrl+F on the wire, so the shell cannot bind it — Ghostty types the command
# instead. Ctrl+F itself runs island-ai (~/.zshrc).
keybind = ctrl+shift+f=text:tmux-sessionizer\n
