# Theme — {{THEME_NAME}}
set -g status-style "bg=default,fg=default"
set -g status-left "#[fg={{THEME_BG}},bg={{THEME_ACCENT}},bold] #S #[bg=default] "
set -g status-right "#[fg={{THEME_ACCENT}}]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg={{THEME_FG_MUTED}}]#h "
set -g window-status-format "#[fg={{THEME_FG_MUTED}}] #I:#W "
set -g window-status-current-format "#[fg={{THEME_ACCENT}},bold] #I:#W "
set -g pane-border-style "fg={{THEME_BG_HIGHLIGHT}}"
set -g pane-active-border-style "fg={{THEME_ACCENT}}"
set -g message-style "bg=default,fg={{THEME_ACCENT}}"
set -g message-command-style "bg=default,fg={{THEME_ACCENT}}"
set -g mode-style "bg={{THEME_ACCENT}},fg={{THEME_BG}}"
setw -g clock-mode-colour "{{THEME_ACCENT}}"
